version: 2
jobs:
  build:
    docker:
    - image: golang:alpine
    steps:
    - checkout
    - run:
        name: Build
        command: ./scripts/build.sh
workflows:
  version: 2
  test:
    jobs:
    - build
